### ISSUE TITLE
Project TODO's

### ISSUE THREAD

**Issue by mfpardini** [mfpardini/movies4u#1]
- [x] create app folder localy
- [x] first commit
- [x] add bootstrap CSS
- [x] define basic style of main page
- [x] test the movie api
- [x] get basic data from de api
